### ISSUE TITLE
Can't run bot.py

### ISSUE THREAD

**Issue by amun3t** [Wans1e/GOD-VIEW#1]
C:\Users\user\Desktop\GOD-VIEW-main>python bot.py
Traceback (most recent call last):
  File "bot.py", line 2, in <module>
    from client.state import ClientStatic
  File "C:\Users\rono\Desktop\GOD-VIEW-main\client\state.py", line 41
    Static.IP = 192.168.0.1
                            ^
SyntaxError: invalid syntax

**Comment by Wans1e** [comment]
The IP has to be a string...
